version: "3.7"
services:
  redis:
    image: redis:5.0.7
    entrypoint: redis-server --appendonly yes
    volumes: 
      - ./data:/data 
    expose:
      - "6379"
  web:
    build: .
    command: sh -c "npm install -no-bin-links && nodemon --inspect=5858"
    depends_on:
      - "redis"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
      - "5858:5858"