version: "3.7"
services:
  web:
    image: bylek/webb-workshop
    depends_on:
      - "redis"
    ports:
      - "80:8000"
  redis:
    image: redis:4.0.14
    entrypoint: redis-server --appendonly yes
    volumes: 
      - ./data:/data 
    expose:
      - "6379"
